name: Publish Image

on:
  push:
    tags:
      - "*"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: docker/setup-buildx-action@v1

      - uses: docker/login-action@v1
        with:
          username: ${{ secret.DOCKERHUB_USERNAME }}
          password: ${{ secret.DOCKERHUB_PASSWORD }}

      - uses: docker/build-push-action@v2
        id: docker_build
        with:
          context: ./packages/server
          file: ./Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
